export TAMALERO_BASE=$PWD
export LD_LIBRARY_PATH=/opt/cactus/lib:$LD_LIBRARY_PATH
export PYTHONPATH=$PYTHONPATH:$PWD
echo "Set PYTHONPATH"
echo $PYTHONPATH
echo "Set LD_LIBRARY"
echo $LD_LIBRARY_PATH
